# Generated by Django 4.2.1 on 2023-05-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0004_tag_delete_tags_idea_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
