# Generated by Django 4.2.1 on 2023-05-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_idea_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created']},
        ),
    ]
