# Generated by Django 4.2.1 on 2023-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_idea_dislike_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=200),
        ),
    ]
