# Generated by Django 4.2.1 on 2023-06-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_review_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created', 'like', 'title']},
        ),
    ]
