# Generated by Django 4.2.1 on 2023-06-16 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
        ('projects', '0010_alter_idea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
